const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path'),http=require('http');
(async()=>{
 const root=path.resolve(__dirname,process.env.THRONEPATH_PACKAGED?'../android-web':'../web'),server=http.createServer((req,res)=>fs.readFile(path.join(root,req.url.split('?')[0]),(e,b)=>{res.writeHead(e?404:200);res.end(e?'':b)}));await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,executablePath:process.env.THRONEPATH_BROWSER||undefined,args:['--no-sandbox']});let failures=0;
 for(const size of [{width:1536,height:566},{width:844,height:300},{width:844,height:390},{width:1280,height:720}]){
 const page=await browser.newPage({viewport:size,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port+'/index.html');await page.evaluate(()=>ThronepathReady);
 const boxes=await page.evaluate(()=>{const art=$('menuArtwork'),fit=getComputedStyle(art).objectFit,scale=(fit==='contain'?Math.min:Math.max)(innerWidth/art.naturalWidth,innerHeight/art.naturalHeight),h=art.naturalHeight*scale,top=fit==='contain'?(innerHeight-h)/2:0;return{logoBottom:top+h*.37,panelTop:$('play').getBoundingClientRect().top,buttons:[...$('mainButtons').children].map(b=>{const r=b.getBoundingClientRect();return{top:r.top,bottom:r.bottom,height:r.height,width:r.width}})}});
 try{assert(boxes.panelTop>=boxes.logoBottom+6,`buttons cover logo: ${JSON.stringify(boxes)}`);assert(boxes.buttons.at(-1).bottom<=size.height-12);assert(boxes.buttons.every(b=>b.height>=28&&b.width>=144));console.log('PASS menu fits',size);}catch(e){failures++;console.error('FAIL menu fits',size,e.message)}
 fs.mkdirSync(path.resolve(__dirname,'../previews/browser1612'),{recursive:true});await page.screenshot({path:path.resolve(__dirname,`../previews/browser1612/home-${size.width}-${size.height}.png`)});
 await page.evaluate(()=>{openOptions();showSettingsTab('achievementsSettings');renderAchievements()});
 const layout=await page.locator('.achievementRow').evaluateAll(rows=>rows.map(row=>{const name=row.querySelector('strong').getBoundingClientRect(),description=row.querySelector('p').getBoundingClientRect(),status=row.querySelector('.achievementStatus').getBoundingClientRect();return{nameBottom:name.bottom,descriptionTop:description.top,descriptionRight:description.right,statusLeft:status.left}}));assert(layout.length>0);assert(layout.every(r=>r.nameBottom<=r.descriptionTop&&r.descriptionRight<=r.statusLeft),'achievement title, description or status overlaps');
 await page.evaluate(()=>{play();load(27);mode='pause';sceneBlend=null;draw()});const perf=await page.evaluate(()=>{const a=performance.now();for(let i=0;i<60;i++){clock+=1/60;draw()}return(performance.now()-a)/60});console.log('Render milliseconds',size,perf.toFixed(2));assert.deepEqual(errors,[]);await page.close();
 }await browser.close();await new Promise(r=>server.close(r));if(failures)process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
