const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path'),http=require('http');
(async()=>{
 const root=path.resolve(__dirname,process.env.THRONEPATH_PACKAGED?'../android-web':'../web');const server=http.createServer((req,res)=>fs.readFile(path.join(root,req.url.split('?')[0]),(e,b)=>{res.writeHead(e?404:200);res.end(e?'':b)}));await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,executablePath:process.env.THRONEPATH_BROWSER||undefined,args:['--no-sandbox']});
 for(const touch of [false,true]){
  const page=await browser.newPage({viewport:touch?{width:844,height:390}:{width:1280,height:720},hasTouch:touch});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:'+server.address().port+'/index.html');await page.evaluate(()=>ThronepathReady);assert.equal(await page.evaluate(()=>GAME_VERSION),'1.6.10');assert.equal(await page.locator('#versionLabel').innerText(),'v1.6.10');assert(!(await page.title()).toLowerCase().includes('beta'));assert.equal(await page.locator('#openCredits').count(),0);assert(await page.locator('#creditsPanel').isHidden());
  await page.locator('#play').click();await page.keyboard.down('ArrowRight');await page.keyboard.press('p');assert.equal(await page.evaluate(()=>mode),'pause');assert.equal(await page.evaluate(()=>input.right),false);const seconds=await page.evaluate(()=>phaseSeconds);await page.evaluate(()=>update(1/120));assert.equal(await page.evaluate(()=>phaseSeconds),seconds);assert(await page.locator('#creditsPanel').isHidden());
  await page.evaluate(()=>window.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyP',key:'p',repeat:true})));assert.equal(await page.evaluate(()=>mode),'pause');await page.keyboard.up('ArrowRight');await page.keyboard.press('p');assert.equal(await page.evaluate(()=>mode),'play');
  await page.evaluate(()=>window.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyP',key:'p',ctrlKey:true})));assert.equal(await page.evaluate(()=>mode),'play');
  assert.equal(await page.locator('#pause').getAttribute('aria-keyshortcuts'),'P Escape');await page.locator('#pause').click();assert.equal(await page.evaluate(()=>mode),'pause');if(!touch)assert(await page.locator('#pauseShortcutHint').isVisible());await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>mode),'play');
  await page.keyboard.press('m');assert.equal(await page.evaluate(()=>mode),'menu');assert(await page.locator('#mainButtons').isVisible());assert(await page.locator('#creditsPanel').isHidden());await page.locator('#play').click();await page.keyboard.press('p');await page.keyboard.press('m');assert.equal(await page.evaluate(()=>mode),'menu');await page.locator('#play').click();
  await page.evaluate(()=>{settings.hudMode='hidden';applySettings()});await page.keyboard.press('p');assert.equal(await page.evaluate(()=>mode),'pause');await page.keyboard.press('p');assert.equal(await page.evaluate(()=>mode),'play');
  await page.evaluate(()=>{openOptions();showSettingsTab('hudSettings')});await page.keyboard.press('p');assert.equal(await page.evaluate(()=>mode),'pause');assert(await page.locator('#settingsPanel').isVisible());assert(await page.locator('#creditsPanel').isHidden());
  await page.evaluate(()=>{goHome();play();load(50);state.won=true;finishStage()});assert(await page.locator('#creditsPanel').isHidden());await page.evaluate(()=>{state.p.x=980;state.p.y=334;state.p.ground=true;state.p.on=4;claimThrone();updateEnding(4)});assert(await page.locator('#creditsPanel').isVisible());assert((await page.locator('#creditsContent').innerText()).includes('Lucas Rodrigues'));assert.equal(await page.evaluate(()=>awards.includes(150)),true);await page.keyboard.press('p');assert.equal(await page.evaluate(()=>mode),'ending');
  await page.evaluate(()=>updateEnding(endingCreditsDuration+4));assert(await page.locator('#postCreditsChoices').isVisible());await page.locator('#creditsBack').click();assert(await page.locator('#creditsPanel').isHidden());assert.equal(await page.locator('#openCredits').count(),0);assert.equal(await page.evaluate(()=>canResetAll()),true);assert.deepEqual(errors,[]);await page.close();
 }
 await browser.close();await new Promise(r=>server.close(r));console.log('1.6.10 browser: P/Esc and button pause, repeat/modifier guards, frozen clock, hidden HUD access, settings guard and credits only after throne passed.');
})().catch(e=>{console.error(e);process.exit(1)});
