const assert=require('assert');const {createRuntime}=require('./runtime.cjs');
const r=createRuntime(),E=r.E;
let failures=[];function test(name,fn){try{fn();console.log('PASS',name)}catch(e){failures.push(name);console.log('FAIL',name,e.message)}}
test('Death cancels gravity and reversed controls, preserves checkpoints',()=>{let s=E.start(50);s.gravity=-1;s.reversed=true;s.flippedPads=[2];s.checkpoint=2;s=E.respawn(s);assert.equal(s.gravity,1);assert.equal(s.reversed,false);assert.equal(s.checkpoint,2);assert.equal(s.flippedPads.length,0)});
test('Every stage starts normally',()=>{for(let n=0;n<51;n++){const s=E.start(n);assert.equal(s.gravity,1);assert.equal(s.reversed,false)}});
test('Laser waiting gates cannot be jumped',()=>{for(let n=5;n<51;n++)for(const m of E.makeLevel(n).machines)if(m.type==='laser')assert(m.h>=270)});
test('Saw repertoire includes air, circular, vertical, pendulum',()=>{const all=Array.from({length:51},(_,n)=>E.makeLevel(n).hazards).flat();for(const motion of ['static','horizontal','vertical','circular','pendulum'])assert(all.some(h=>h.motion===motion),motion)});
test('Saved qualities migrate to high',()=>{for(const q of ['low','medium','high']){const t=createRuntime({'thronepath-settings-v1':JSON.stringify({quality:q})});assert.equal(t.run('settings.quality'),'high')}});
test('Camera follows a jump before landing',()=>{r.run("load(0);mode='play';queuedJump=true;update(1/120)");const y=r.run('camY');r.run('for(let i=0;i<15;i++)update(1/120)');assert(Math.abs(r.run('camY')-y)>1)});
if(failures.length)process.exitCode=1;
test('Additional traps include crushers and rolling stones',()=>{const hs=Array.from({length:51},(_,n)=>E.makeLevel(n).hazards).flat();assert(hs.some(h=>h.type==='crusher'));assert(hs.some(h=>h.type==='boulder'))});
test('Gravity pad does not toggle while contact continues',()=>{let s=E.start(11);const i=s.level.pads[0],b=s.level.platforms[i];s.level.hazards=[];s.level.machines=[];s.level.enemies=[];s.level.springs=[];s.pursuits=[];Object.assign(s.p,{x:b.x+30,y:b.y-50,ground:true,on:i,vy:0});for(let f=0;f<40;f++)E.step(s,{},1/120);assert.equal(s.gravity,-1);s=E.respawn(s);assert.equal(s.gravity,1);Object.assign(s.p,{x:b.x+30,y:b.y-50,ground:true,on:i,vy:0});E.step(s,{},1/120);assert.equal(s.gravity,-1)});
test('Input adapters merge gamepad and keyboard before inversion',()=>{r.env.navigator.getGamepads=()=>[{connected:true,axes:[1],buttons:[{pressed:true}]}];assert(r.run('readActions().right'));r.run("load(0);mode='play';state.reversed=true;state.reverseUntil=10;update(1/120)");assert(r.run('state.p.vx<0'));r.env.navigator.getGamepads=()=>[];assert(!r.run('readActions().right'))});
if(failures.length)process.exitCode=1;
test('Active laser catches a full jump; off interval is passable',()=>{const n=Array.from({length:51},(_,n)=>n).find(n=>E.makeLevel(n).machines.some(m=>m.type==='laser'));for(const active of [true,false]){const s=E.start(n),m=s.level.machines.find(m=>m.type==='laser'),b=s.level.platforms[m.platform];s.level.machines=[m];s.level.hazards=[];s.level.enemies=[];s.level.springs=[];s.level.pads=[];s.pursuits=[];s.t=(active?2.5:.1)-m.phase;Object.assign(s.p,{x:b.x+b.w*.54-10,y:b.y-155,vy:0,ground:false,on:-1});E.step(s,{},1/120);assert.equal(s.dead,active)}});
test('Quality never changes the simulation',()=>{let expected;for(const q of ['low','medium','high']){r.run(`settings.quality='${q}';applySettings()`);const s=E.start(30);for(let i=0;i<120;i++)E.step(s,{right:true,jump:i===20},1/120);const result=JSON.stringify(s);if(expected)assert.equal(result,expected);expected=result;}});
test('Temporary controls expire and restart clears all effects',()=>{const s=E.start(17),z=s.level.controlZones[0],b=s.level.platforms[z.platform];s.level.hazards=[];s.level.enemies=[];s.level.machines=[];s.level.springs=[];s.pursuits=[];Object.assign(s.p,{x:b.x+30,y:b.y-50,on:z.platform,ground:true});E.step(s,{},1/120);assert(s.reversed);assert.equal(s.message,'CONTROLES INVERTIDOS!');for(let f=0;f<1000;f++)E.step(s,{},1/120);assert(!s.reversed);assert.equal(E.start(17).gravity,1)});
if(failures.length)process.exitCode=1;

