const assert=require('assert'),{createRuntime}=require('./runtime167.cjs');
const r=createRuntime({}, {touch:true});
assert.equal(r.run('GAME_VERSION'),'1.6.9');
assert.equal(r.run('ACHIEVEMENTS.length'),150);assert.equal(r.run('ACHIEVEMENTS.at(-1)[0]'),150);
assert.equal(r.run('ACHIEVEMENTS.at(-1)[3]'),'completions');
r.run('play();load(50);state.won=true;finishStage()');
assert(r.run('castleRoom'));assert.equal(r.run('mode'),'play');assert(!r.run('awards.includes(150)'));assert(!r.run('best[50]!==undefined'));
assert.equal(r.run('claimThrone()'),false,'Throne must be reached before it can be claimed');
r.run('state.p.x=state.level.door.x-20;state.p.y=state.level.platforms.at(-1).y-state.p.h;state.p.on=state.level.platforms.length-1;state.p.ground=true;draw()');
assert.equal(r.run('claimThrone()'),true);assert.equal(r.run('mode'),'ending');assert(r.run('awards.includes(150)'));assert.equal(r.run('metrics.completions'),1);assert.equal(r.run('claimThrone()'),false);
r.run('updateEnding(4)');assert(!r.elements.get('creditsPanel').hidden);assert(!r.elements.get('creditsBack').hidden);
r.run('goHome();openCredits();goHome()');assert.equal(r.run('mode'),'win','Reviewing credits after completion must preserve the completed journey');r.run('play()');assert.equal(r.run('current'),0);
const old={unlocked:50,best:{50:100},falls:4,metrics:{seconds:3661,deaths:20},awards:[1,30,150],cleanPhases:[51]};
const migrated=createRuntime({'porta2d-v1':JSON.stringify(old),'thronepath-settings-v1':JSON.stringify({compact:false,showTime:true})});
assert.equal(migrated.run('settings.hudMode'),'full');assert.equal(migrated.run('metrics.totalSeconds'),3661);assert.equal(migrated.run('metrics.completions'),1);assert(migrated.run('awards.includes(30)&&awards.includes(150)'));
const tutorialOnly=createRuntime({'porta2d-v1':JSON.stringify({awards:[150],metrics:{tutorialWatched:10}})});assert(tutorialOnly.run('awards.includes(30)'));assert(!tutorialOnly.run('awards.includes(150)'));
const stats=createRuntime({'porta2d-v1':JSON.stringify({falls:3,metrics:{seconds:4000,deaths:50,totalSeconds:90000},playedDates:['2026-10-09']})});stats.run('play();update(1/120)');
assert(stats.run('playedDates.length>=1'));assert(stats.run('metrics.totalSeconds>90000'));stats.run('resetDeaths()');assert.equal(stats.run('metrics.deaths'),50);
stats.run('metrics.seconds=0;renderProgressStatistics()');assert(stats.elements.get('progressHours').textContent.includes('25h'));
for(let n=0;n<51;n++)r.run('load('+n+');draw()');
console.log('1.6.9: gated throne ending, 150th award, legacy awards and lifetime stats migration, repeated claim guard, credits and 51 renders passed');
